name: better_notifier
description: "Better Notifier is a Dart package that simplifies state management by enhancing the capabilities of ValueNotifier. This package introduces powerful abstractions and extensions for managing ValueNotifier instances, making them more flexible, efficient, and developer-friendly. It is particularly suited for applications requiring advanced state management and reactive programming."
version: 0.0.1
repository: https://github.com/dronn1k-org/better_notifier
issue_tracker: https://github.com/dronn1k-org/better_notifier/issues

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: